config/routes.rb
Rails.application.routes.draw do
  	devise_for :users

  	get "ads/:id", to: 'application#show'
	resources :companytypes, :ads

	resources :companies do 
		resources :flyers
	end

	resources :campaigns do 
		resources :runs
	end

	resources :qr_codes, only: [:new, :create]
	
	# companies 
	get "companies/:id/delete", to: 'companies#delete', as: 'delete_company'
	get "campaigns/:id/delete", to: 'campaigns#delete', as: 'delete_campaign'
	#get "runs/:id/download", to: 'companies#download', as: 'download_run'

	# runs
	get "runs/:id/delete", to: 'runs#delete', as: 'delete_run'
	get "runs/:id/newstatus", to: 'runs#newstatus', as: 'newstatus_run'
	post "/runs/:id/newstatus", to: 'runs#changestatus', as: 'changestatus_run'

	# flyers
	get "flyers", to: 'flyers#index', as: "flyers"
	post "flyers/:id/confirm", to: 'flyers#confirm', as: "confirm_flyer"
	delete "flyers/:id", to: 'flyers#destroy', as: "destroy_flyer"

	# landing page
	post "landings", to: 'landings#createSubscription'
	
	root :to => "landings#index"  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, :except => [:show]

  # GET /ads/1
  # GET /ads/1.json
  def show
    #binding.pry
    @ad = Ad.find(params[:id])
    Ad.visits(@ad)
    Campaign.visits(@ad)
    redirect_to Ad.url(@ad) # "https://www.facebook.com"
  end

  protected

	def after_sign_in_path_for(resource)
		if current_user.companies.empty?
      new_company_path
    else
      companies_path
    end
	end

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :firstname, :lastname, :country, :city]) 
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :firstname, :lastname, :country, :city])     
	end  		
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		content_for(:title) { page_title }
	end
	def subtitle(page_subtitle)
		content_for(:subtitle) { page_subtitle }
	end
	def paragraph(page_paragraph)
		content_for(:paragraph) { page_paragraph }
	end

	def header(type, text)
		case type
			when "companies"
				content_for(:companies) { text } 
			when "runs"
				content_for(:runs) { text }
			when "campaigns"
				content_for(:campaigns) { text }
			when "runs#index"
				content_for(:runs_index) { text }				
			when "runs#new"
				content_for(:runs_new) { text }								
			when "runs#status"
				content_for(:runs_status) { text }	
			when "flyers#index"
				content_for(:flyer) { text }							
			when "statistics"
				content_for(:statistics) { text }					
		end
	end
end

app/views/application/partials/_footer.html.erb
                </div>
            </div>
        </div>




        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <%= link_to "Private Policy", "/privacy.html"%>
                        </li>

                    </ul>
                </nav>
            </div>
        </footer>

    </div>
</div>

app/views/application/partials/_navbar.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="azure" data-image="">

    <!--https://s3.eu-central-1.amazonaws.com/freeads/sidebar-4.jpg

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <div class="simple-text">
                    Free Ads Worldwide
                </div>
            </div>

            <ul class="nav">
                <!--li>
                    <a href="dashboard.html">
                        <i class="pe-7s-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li-->
                <li class="" id="company">
                    <% if current_user.present? && current_user.companies.length > 0 %>
                        <%= link_to companies_path, {class: "navbarLinks", id: "Companies" }  do %>
                            <i class="pe-7s-home"></i>
                            <!--i class="pe-7s-culture"></i-->
                            <p>Home</p>
                        <% end %>
                    <% elsif current_user.present? %>
                        <%= link_to new_company_path, {class: "navbarLinks", id: "Account" } do %>
                            <i class="pe-7s-culture"></i>
                            <p>New Company</p>
                        <% end %>
                    <% end %>
                </li>            
                <!--li>
                    <%#= link_to companies_path, {class: "navbarLinks" } do %>
                        <i class="pe-7s-culture"></i>
                        <p>Companies</p>
                    <%# end %> 
                </li-->                  
                <li class="">
                    <%= link_to campaigns_path, {class: "navbarLinks hidden-md hidden-lg" } do %>
                        <i class="pe-7s-news-paper"></i>
                        <p>Campaigns</p>
                    <% end %>
                </li>
                <% last_campaign = current_user.campaigns.last if current_user.present? && current_user.campaigns.present? %>
                <!--li class="">
                    <%#= link_to campaign_runs_path(campaign), {class: "navbarLinks"} do %>
                        <i class="pe-7s-print"></i>
                        <p>Print Orders</p>
                    <%# end %>
                </li-->
                <%# last_campaign = current_user.campaigns.last %>
                <% if last_campaign.present? %>
                    <% if last_campaign.runs.where.not(:status => "completed").size == 0 %>
                        <li class="">
                            <%= link_to new_campaign_run_path(last_campaign), { class: "navbarLinks" } do %>
                                <i class="pe-7s-print" aria-hidden="true"></i>
                                <p>Create Print</p>
                            <% end %>
                        </li>
                        <li class="hidden-xs hidden-sm hidden-md hidden-lg">
                            <%= link_to companies_path(last_campaign), { class: "navbarLinks", id: "printButton"} do %>
                                <i class="pe-7s-print" aria-hidden="true"></i>
                                <p>Create Print</p>
                            <% end %>
                        </li>

                    <% end %>
                    <% last_run = current_user.runs.where.not(:status => "completed").order(created_at: :desc).last %>
                    <% if last_run.present? %>
                        <li class="">
                            <%= link_to campaign_run_path(last_run.campaign, last_run, format: "pdf"), {class: "navbarLinks"} do %>
                                <i class="pe-7s-cloud-download" aria-hidden="true"></i>
                                <p>Fliers Pdf</p>
                            <% end %>
                        </li>

                        <% if current_user.runs.last.status == "to distribute" %>
                            <li class="">
                                <%= link_to  newstatus_run_path(last_run), {class: "navbarLinks"} do %>
                                    <i class="pe-7s-check" aria-hidden="true"></i>
                                    <p>Fliers Distributed</p>
                                <% end %>
                            </li>
                        <% end %>                                               
                    <% end %>
                <% end %> <!-- last_campaign.present? -->
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <%= link_to edit_user_registration_path,{class: "navbarLinks", id: "Account"} do %>
                                Account
                            <% end %>
                        </li>
                        <li>
                            <%= link_to destroy_user_session_path, method: :delete do %>
                                Log out
                            <% end %>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">