config/routes.rb
Rails.application.routes.draw do
  	devise_for :users

  	get "ads/:id", to: 'application#show'
	resources :companytypes, :ads

	resources :companies do 
		resources :flyers
	end

	resources :campaigns do 
		resources :runs
	end

	resources :qr_codes, only: [:new, :create]
	
	# companies 
	get "companies/:id/delete", to: 'companies#delete', as: 'delete_company'
	get "campaigns/:id/delete", to: 'campaigns#delete', as: 'delete_campaign'
	#get "runs/:id/download", to: 'companies#download', as: 'download_run'

	# runs
	get "runs/:id/delete", to: 'runs#delete', as: 'delete_run'
	get "runs/:id/newstatus", to: 'runs#newstatus', as: 'newstatus_run'
	post "/runs/:id/newstatus", to: 'runs#changestatus', as: 'changestatus_run'

	# flyers
	get "flyers", to: 'flyers#index', as: "flyers"
	post "flyers/:id/confirm", to: 'flyers#confirm', as: "confirm_flyer"
	delete "flyers/:id", to: 'flyers#destroy', as: "destroy_flyer"

	# landing page
	post "landings", to: 'landings#createSubscription'
	
	root :to => "landings#index"  
end

app/models/company.rb
class Company < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :campaigns, :dependent => :destroy
	has_many :ads, :dependent => :destroy
	has_many :flyers, inverse_of: :company, :dependent => :destroy
	belongs_to :companytype

	accepts_nested_attributes_for :flyers, reject_if: lambda {|attributes|	attributes['image'].blank?} 

	validates_presence_of :name, :companytype, :description, :url
	#validates_associated :users
	#validates_presence_of :users
	validates :name, length: {minimim: 2, maximum: 24}
	#validates :description, length: {minimum: 70, maximum: 1500}


	def self.url(company)
		url = company.url
		
		if url.start_with?("http://")
			return url
		elsif url.start_with?("https://")
			return url
		elsif url.start_with?("https://www.")
			return url
		elsif url.start_with?("www.")
			return url = "https://" + url
		else 
			return url = "https://www." + url
		end
	end  	
end

app/models/companytype.rb
class Companytype < ApplicationRecord
	has_many :companies, :dependent => :destroy

	validates_presence_of :name
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def index	
		@companies = current_user.companies
		@campaigns = current_user.campaigns
		@runs = current_user.runs.where.not(:status => "completed")
		@campaign = Campaign.find(params[:format]) if params[:format].present?
		@all_companies = Company.all

		@style = ["skills first", "skills second", "skills third", "skills fourth"]

		@total_visits = Ad.all.sum(:visits)
		@partial_visits = Ad.all.group(:company_id).sum(:visits)		
		@run = Run.new
		flash[:warning_campaign] = "Click on the print icon to create your print order." if current_user.runs.where.not(:status=>"completed").empty?						if current_user.runs.where.not(:status => "completed").empty?
	end

	def new
		flash[:notice] = "Now you can register your company and configure your first Campaign" if current_user.companies.empty?
		@company = Company.new
		@campaign = Campaign.new
		@company.flyers.build
	end

	def create
		@company = Company.new(company_params)
		#@company.flyers.first.company_id = @company.id
		@campaign = Campaign.new(campaign_params)
		if @company.validate(company_params) #&& @campaign.validate(campaign_params)
			@company.save
			current_user.companies << @company
			# create the campaign for the company
			if params[:company].has_key?(:campaign) &&  campaign_params.present? 
				@campaign.company_id = @company.id 
				@campaign.save 
				flash[:warning_campaign] = "Click on the print icon to create your first print order." if current_user.runs.empty?						
			end
			flash[:notice] = "Your Company was saved"
			redirect_to action: "index"
		else
			flash[:error] = "An error occurred, the company was not saved"
			render "new"
		end
	end

	def download
	@run = Run.find(params[:id])
	@ads = @run.ads
		respond_to do |format|
		  format.html
		  format.pdf do
		    pdf = RunPdf.new(@run, @ads)
		    #pdf.text "Hello World"
		    send_data pdf.render, filename: "Print Order N.#{@run.id}.pdf",
		                          type: "application/pdf"
		  end
		end
	end  
  
	def edit 
		@company = Company.find(params[:id])
		@company.flyers.build
	end

	def update
		#binding.pry
		@company = Company.find(params[:id])
		if @company.update_attributes(company_params)
			flash[:notice] = "Your Company was saved"
			redirect_to action: "index"
		else
			flash[:error] = "An error occurred, the company was not saved"
			render "edit"
		end
	end

	def show
		@company = Company.find(params[:id])
	end

	def delete
		@company = Company.find(params[:id])
	end

	def destroy
		@company = Company.find(params[:id])
		if @company.destroy
			flash[:notice] = "The Company was destroyed"
			redirect_to action: "index"
		else
			flash[:error] = "An error occurred, the company was not saved"
			redirect_to action: "index"
		end
	end

	private

	def company_params 
		params.require(:company).permit(:companytype_id, :name, :title, :description, :url, flyers_attributes: [:company_id, :language_id, :image]) 
	end
	def campaign_params		
		params.require(:company).require(:campaign).permit(:name, :worldwide, :america, :europe, :asia, :oceania, :campaigntype_id) 
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/delete.html.erb
<% header("companies","Delete Company") %>
<%= render "shared/partials/alert", text: @text %>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
               <h2><%= yield(:companies) %></h2>
            </header>
            <div class="panel-body">
            <%= link_to "Delete", {:action => "destroy"}, :method => :delete, :class => "btn btn-warning wideButton btn-fill btn-main" %>
            <%= link_to "Cancel", companies_path, :class => "btn btn-primary wideButton btn-fill btn-main" %>
            </div>
        </section>   
    </div>
</div>

app/views/companies/edit.html.erb
<% header("companies","Create Company") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:companies) %></h4>
</div>  
<div class="content">
    <%= simple_form_for @company do |f| %>
      <% if @company.errors['base'].present? %>
        <span class="help-block error"><%= @company.errors['base'][0] %></span>
      <% end %>     
      <%= render 'partials/error_messages', object: @company %>
      <%= f.input :name %>
      <%= f.association :companytype, prompt: "Choose a type", class: "form-control" %>
      <%#= f.input :title %>
      <%= f.input :description, label: "Description 200-360 Characters", as: :text, class: "description" %>
      <span class="countdown"></span>
      <%= f.input :url %>

      <!-- flyers#new -->
      <% if @company.flyers.present? %>
        <% flyers_present = true %>
      <% else %>
        <% flyers_present = false %>
      <% end %>

      <%= f.input :own_style, label: "Upload own flyer design?", as: :radio_buttons, :input_html => { 'data-toggle' => "radio" }, :checked => flyers_present %>
      <%= f.fields_for :flyers do |flyer| %>
        <div class="flyer_fields">
          <% if flyer.object.id.present? %>
            <% var_bool = true %>
          <% else %>
            <% var_bool = false %>
          <% end %>
          <% unless var_bool %>
            <%= flyer.label :language_id, "Select the Language of the Flyer" %>
          <% else %>
            <%= flyer.label :language_id, "Uploaded Languages" %>
            <%= link_to "Delete Flyer", { :controller => "flyers", :action => "destroy", :company_id => flyer.object.company_id, :id => flyer.object.id}, method: :delete %> 
          <% end %>
          <%= flyer.select(:language_id, Language.all.collect{|l| [l.name, l.id]}, {defualt: "EN", selected: flyer.object.language_id}, {:class => "form-control", disabled: var_bool }) %>
          <% unless var_bool %>
            <%= flyer.label :image, "add your flier image..." %>
            <%= flyer.file_field :image, class: "form-control" %>
          <% end %>
        </div>
      <% end %>      
      
      <%= link_to "Back", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>
      <%= f.button :submit, class: "btn btn-info btn-fill pull-right btn-main" %>
      <div class="clearfix"></div>
    <% end %>
</div>
<%= render partial: "shared/partials/formfooter" %>

app/views/companies/home.html.erb
<div id="regions_div" style="width: 900px; height: 500px;"></div>

app/views/companies/index.html.erb
<%= render partial: "companies/partials/statisticsbar" %>

<% if @companies.length > 0 %>
<% header("companies","Your Companies") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:companies) %></h4>
</div>  
<div class="content table-responsive table-full-width">
    <table class="table table-hover table-striped">
        <thead class="row">
            <th>Name</th>
        	<th class="hidden-xs">Type</th>
        	<th>Website</th>
            <th class="options col-xs-5 col-sm-3 col-md-2">Options</th>
        </thead>
        <tbody class="row">
            <% @companies.each do |company| %>
            <tr>
            	<td><%= company.name %></td>
            	<td class="hidden-xs"><%= company.companytype.name %></td>
            	<td>
                    <%= link_to Company.url(company) do %>
                    <i class="pe-7s-link"></i>
                    <% end %>
                </td>
                <td class="options col-xs-5 col-sm-3 col-md-2">
                    <div class="btn-group" id="btn-group">
                     <%= link_to company_path(company.id), {class: "btn btn-primary", 'rel' => 'tooltip', 'data-placement' => 'left', 'title'=>"Display Company"} do %>
                     <i class="fa fa-arrow-right" aria-hidden="true"></i>
                     <% end %>
                     <%= link_to edit_company_path(company.id), {class: "btn btn-success", 'rel' => 'tooltip', 'data-placement' => 'top', 'title'=>"Edit Company"}  do %>
                     <i class="fa fa-pencil" aria-hidden="true"></i>
                     <% end %>
                     <%= link_to delete_company_path(company.id), {class: "btn btn-danger", 'rel' => 'tooltip', 'data-placement' => 'right', 'title'=>"Delete Company"}  do %>
                     <i class="fa fa-trash-o" aria-hidden="true"></i>
                     <% end %>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>

</div>
<%= render partial: "shared/partials/formfooter" %>
<%= render template: "campaigns/index" %>
<div id="runForm">
    <%= render template: "runs/new" if params[:format].present? %>
</div>
<%= render template: "runs/index" %>
<%= render partial: "shared/links/companies_links" %>
<% else %>
<%= render partial: "shared/links/companies_links" %>
<% end %>

app/views/companies/new.html.erb
<% header("companies","Create Company") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:companies) %></h4>
</div>  
<div class="content">
    <%= simple_form_for @company do |f| %>
      
      <div class="card">
          <%= image_tag "growstartup_english_description.png", class:"companyPicture" %>
          <!--img src="https://s3.eu-central-1.amazonaws.com/freeads/Growstartup+English+Description.png", class= "companyPicture"-->
      </div>

      <% if @company.errors['base'].present? %>
        <span class="help-block error"><%= @company.errors['base'][0] %></span>
      <% end %>     
      <%= render 'partials/error_messages', object: @company %>
      <%= f.input :name %>
      <%= f.association :companytype, prompt: "Choose a type", class: "form-control" %>
      <%= f.input :title %>
      <%= f.input :description, label: "Description - Include up to 6 Best Features", as: :text, class: "description" %>
      <span class="countdown"></span>
      <%= f.input :url %>

      <!-- flyers#new -->

      <%= f.input :own_style, label: "Upload your own flyer design? We use A4 paper size (210 x 297 cm)", as: :radio_buttons, :input_html => { 'data-toggle' => "radio" }, :checked => false %>
      <%#= f.input :worldwide, as: :radio_buttons,:input_html => { 'data-toggle' => "radio" }, wrapper_html: {id: 'worldwide'} %>
      <%= f.fields_for :flyers do |flyer| %>
        <%#= flyer.select(:company_id, current_user.companies.collect {|p| [ p.name, p.id ]}, {:selected => @company.id}) %>
        <div class="flyer_fields">
          <%= flyer.label :language_id, "Select the Language of the Flyer"%>
          <%= flyer.select(:language_id, Language.all.collect{|l| [l.name, l.id]}, {:selected => "EN"}, {:class => "form-control"}) %>
          <%= flyer.label :image, "add your flier image..." %>
          <%= flyer.file_field :image, class: "form-control" %>
        </div>
      <% end %>      

      <div class="clearfix"></div>
</div>
<%= render partial: "shared/partials/formfooter" %>

<% subtitle "Advertising Campaign" %> 
<%= render "shared/partials/formsubheader" %>
<div class="content">
      <%= f.simple_fields_for @campaign do |c| %>
        <% if @campaign.errors['base'].present? %>
          <span class="help-block error"><%= @campaign.errors['base'][0] %></span>
        <% end %>  
        <%= c.input :name %>
        <%= c.input :worldwide, as: :radio_buttons, :input_html => { 'data-toggle' => "radio" }, wrapper_html: {id: 'worldwide'} %>
        <div class="checkboxes">
          <div class="checkbox">
            <%= c.label :america %> 
            <%= c.check_box :america, { value: "0", 'data-toggle' => "checkbox"} %>
          </div> 
          <div class="checkbox">
            <%= c.label :europe %> 
            <%= c.check_box :europe, { value: "0", 'data-toggle' => "checkbox"} %>
          </div> 
          <div class="checkbox">
            <%= c.label :asia %> 
            <%= c.check_box :asia, { value: "0", 'data-toggle' => "checkbox"} %>
          </div> 
          <div class="checkbox">
            <%= c.label :oceania %> 
            <%= c.check_box :oceania, { value: "0", 'data-toggle' => "checkbox"} %>
          </div>                                                                  
        </div>
        <%= c.association :campaigntype, prompt: "Choose a Campaign type", class: "form-control" %>
        <!--div class="form-group select required">        
          <%#= c.label :company_id %>
          <%# if @company.present? %>
            <%#= c.select(:company_id, current_user.companies.collect {|p| [ p.name, p.id ]}, {:selected => @company.id }, {:class => "form-control"}) %> 
          <%# else %>
            <%#= c.select(:company_id, current_user.companies.collect {|p| [ p.name, p.id ]}, {}, {:class => "form-control"}) %> 
          <%# end %>                
        </div> 
      <% end %> <! end of simple fields for -->


      <%= link_to "Back", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>
      <%= f.button :submit, class: "btn btn-info btn-fill pull-right btn-main" %>
      <div class="clearfix"></div>
<% end %> <!-- end of the form -->
</div>
<%= render partial: "shared/partials/formfooter" %>

app/views/companies/show.html.erb
<% header("companies","Display Company") %>
<%= render "shared/partials/formheader", title: @title %>
<div class="header">
    <h4 class="title"><%= yield(:companies) %></h4>
</div>  
<div class="content">
    <%= simple_form_for @company do |f| %>
      <%= f.input :name, disabled: true %>
      <%= f.association :companytype, prompt: "Choose a type", class: "form-control", disabled: true %>
      <%#= f.input :title, disabled: true %>
      <%= f.input :description, as: :text, disabled: true %>
      <%= f.input :url, ad: :url, disabled: true %>
      <%= link_to "Back", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>
      <%#= f.button :submit, class: "btn btn-info btn-fill pull-right" %>
      <div class="clearfix"></div>
    <% end %>
</div>
<%= render partial: "shared/partials/formfooter" %>
<%= render partial: "shared/links/companies_links" %>

<% flyer_url = nil %>
<% @company.flyers.each do |flyer| %>
  <% flyer_url = flyer.image.url if flyer.image.url.present? %>
<% end %>

<%= image_tag(flyer_url, alt: 'Image', class: 'flyer_image') if flyer_url.present? %>