config/routes.rb
Rails.application.routes.draw do
  	devise_for :users

  	get "ads/:id", to: 'application#show'
	resources :companytypes, :ads

	resources :companies do 
		resources :flyers
	end

	resources :campaigns do 
		resources :runs
	end

	resources :qr_codes, only: [:new, :create]
	
	# companies 
	get "companies/:id/delete", to: 'companies#delete', as: 'delete_company'
	get "campaigns/:id/delete", to: 'campaigns#delete', as: 'delete_campaign'
	#get "runs/:id/download", to: 'companies#download', as: 'download_run'

	# runs
	get "runs/:id/delete", to: 'runs#delete', as: 'delete_run'
	get "runs/:id/newstatus", to: 'runs#newstatus', as: 'newstatus_run'
	post "/runs/:id/newstatus", to: 'runs#changestatus', as: 'changestatus_run'

	# flyers
	get "flyers", to: 'flyers#index', as: "flyers"
	post "flyers/:id/confirm", to: 'flyers#confirm', as: "confirm_flyer"
	delete "flyers/:id", to: 'flyers#destroy', as: "destroy_flyer"

	# landing page
	post "landings", to: 'landings#createSubscription'
	
	root :to => "landings#index"  
end

app/models/ad.rb
class Ad < ApplicationRecord
	belongs_to :company
	belongs_to :run

	def self.visits(ad)
		ad.visits += 1
		ad.save
	end


	def self.url(ad)
		url = ad.company.url
		
		if url.start_with?("http://")
			return url
		elsif url.start_with?("https://")
			return url
		elsif url.start_with?("https://www.")
			return url
		elsif url.start_with?("www.")
			return url = "https://" + url
		else 
			return url = "https://www." + url
		end
	end  

	def self.adUrl(ad)
		return url = "growstartups.xyz/ads/" + ad.id.to_s
	end	

	def self.urlShortner(ad)
		url = "https://" + Ad.adUrl(ad)
		#url = "https://growstartups.xyz/ads/221"
		authorize = UrlShortener::Authorize.new ENV['bitlylogin'], ENV['bitly_api_key']
		client = UrlShortener::Client.new authorize
		shorten = client.shorten(url)
		return shorten.urls
	end

	def self.postSimple(company, run, boolean)
     	#company.ads_received += 1 if 
     	Ad.create(:company_id => company.id, :run_id => run.id, :selfpromotion => boolean)
	end	

	def self.postMultiple(campaigns, ads, run)
		unless ads == nil
		    campaigns.each do |c|
		      ads.times do
		      	Ad.create(:company_id => c.company.id, :run_id => run.id, :selfpromotion => false, :visits => 0)
		      end
		      # add field for taking count of this number of adds in the campaing.adsreceived
		      c.ads_received += ads
		      c.save
		    end	
		end
	end	
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	has_many :runs, :dependent => :destroy
	belongs_to :campaigntype
	belongs_to :company

	validates_presence_of :name, :company_id, :campaigntype_id
	validates_uniqueness_of :company_id, scope: [:campaigntype_id], :message => "you can create only one type of Campaign for each company"
	
	def self.filtered(run)
	    campaigns = Campaign.where.not(:company_id => run.campaign.company.id).rewhere(:campaigntype_id => run.campaign.campaigntype_id)
	    return campaigns
	end	

	def self.visits(ad)
		promoter_campaign = ad.run.campaign
		campaigntype =  ad.run.campaign.campaigntype
		company_campaign = ad.company.campaigns.where(:campaigntype_id => campaigntype.id).first

		promoter_campaign.givenvisits += 1 unless ad.selfpromotion  
		company_campaign.obtainedvisits += 1 unless ad.selfpromotion

		promoter_campaign.save
		company_campaign.save
		promoter_campaign.reload
		company_campaign.reload
		promoter_campaign.visitratio = promoter_campaign.givenvisits / promoter_campaign.obtainedvisits 
		company_campaign.visitratio = company_campaign.givenvisits / company_campaign.obtainedvisits 
		promoter_campaign.save
		company_campaign.save
	end	
end

app/models/campaigntype.rb
class Campaigntype < ApplicationRecord
	validates_presence_of :name
end

app/models/company.rb
class Company < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :campaigns, :dependent => :destroy
	has_many :ads, :dependent => :destroy
	has_many :flyers, inverse_of: :company, :dependent => :destroy
	belongs_to :companytype

	accepts_nested_attributes_for :flyers, reject_if: lambda {|attributes|	attributes['image'].blank?} 

	validates_presence_of :name, :companytype, :description, :url
	#validates_associated :users
	#validates_presence_of :users
	validates :name, length: {minimim: 2, maximum: 24}
	#validates :description, length: {minimum: 70, maximum: 1500}


	def self.url(company)
		url = company.url
		
		if url.start_with?("http://")
			return url
		elsif url.start_with?("https://")
			return url
		elsif url.start_with?("https://www.")
			return url
		elsif url.start_with?("www.")
			return url = "https://" + url
		else 
			return url = "https://www." + url
		end
	end  	
end

app/models/company_run.rb
class CompanyRun < ApplicationRecord
end

app/models/companytype.rb
class Companytype < ApplicationRecord
	has_many :companies, :dependent => :destroy

	validates_presence_of :name
end

app/models/flyer.rb
class Flyer < ApplicationRecord
	mount_uploader :image, FlyerUploader

	belongs_to :company
	#belongs_to :language

	#validates_presence_of :company_id, :language_id
end

app/models/language.rb
class Language < ApplicationRecord
	has_many :runs
end

app/models/print.rb
class Print < ApplicationRecord
	belongs_to :run

	#validates_presence_of :company_number, :print
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/run.rb
class Run < ApplicationRecord
	require 'prawn'

	belongs_to :campaign
	belongs_to :language
	has_many :prints, inverse_of: :run, :dependent => :destroy
	has_many :ads, :dependent => :destroy

	accepts_nested_attributes_for :ads, :prints

	validates_presence_of :campaign_id, :city, :location
	#validates :ownads, numericality: { greater_than_or_equal_to: 0, less_than: 75}
	#validates :runprintnumber, numericality: { greater_than: 0, less_than: 80}
	#validates_with RunValidator, fields: [:current_user, :campaign_id, :status]

	def self.nextStatus(run)
		case run.status
		when "to distribute"
			return "completed"
		end
	end

	def self.operator(num, den)
		unless num == 0 || den.size == 0
			ads = (num / den.size).to_i 
			return ads 
		end
	end

  	def self.createAds(run)
	    campaign = run.campaign
	    company = campaign.company  		

	    run.ownads.times do
	      Ad.create(:company_id => company.id, :run_id => run.id, :selfpromotion => true, :visits => 0)
	    end

		if run.ownads < run.runprintnumber
		    otherads = run.runprintnumber - run.ownads
		    firstgroup = (otherads*0.70).ceil
		    secondgroup = otherads - firstgroup 

		    campaigns = Campaign.filtered(run)
		    campaigns = campaigns.joins(:runs).where('runs.status' => "completed").distinct
		    
		    campaigns = campaigns.order(ratio_visits: :desc, created_at: :asc) # ads_received: :asc, 

		    campaigns = Campaign.filtered(run) if campaigns.size == 0 || firstgroup > campaigns.size

		    if firstgroup > campaigns.size
		    	ads = Run.operator(firstgroup, campaigns)
		    else
		    	numberofcompanies = ( firstgroup * 0.5 ).to_i
		    	campaigns = campaigns.limit(numberofcompanies)
		    	ads = 2
		    end

			Ad.postMultiple(campaigns, ads, run)

		    if firstgroup.odd? 
		      Ad.create(:company_id => campaigns[0].company.id, :run_id => run.id, :selfpromotion => false, :visits => 0)
		      campaigns[0].ads_received += 1
		      campaigns[0].save
		    end

			campaigns = Campaign.filtered(run)
			campaigns = campaigns.limit(secondgroup) if campaigns.size > secondgroup 

			ads = Run.operator(secondgroup, campaigns)    
		    Ad.postMultiple(campaigns, ads, run) unless secondgroup == 0
		end
 	end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    # associations
 	has_and_belongs_to_many :companies, :dependent => :destroy
 	has_many :campaigns, through: :companies, :dependent => :destroy
 	has_many :runs, through: :campaigns, :dependent => :destroy

 	# validations
 	validates_presence_of :country, :city, :email

 	def country_name
    	country = ISO3166::Country[country_code]
    	country.translations[I18n.locale.to_s] || country.name
  	end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/flyers_helper.rb
module FlyersHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
	<%# binding.pry %>
  <div class="alert alert-block alert-danger fade in">
    <p><strong>This form contains <%= pluralize(object.errors.count, 'error') %>.</strong></p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>  
<% end %>    

app/views/partials/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_url('apple-icon-57x57.png') %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_url('apple-icon-60x60.png') %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_url('apple-icon-72x72.png') %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_url('apple-icon-76x76.png') %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_url('apple-icon-114x114.png') %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_url('apple-icon-120x120.png') %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_url('apple-icon-144x144.png') %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_url('apple-icon-152x152.png') %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_url('apple-icon-180x180.png') %>">
<link rel="icon" type="image/png" sizes="192x192"  href="<%= image_url('android-icon-192x192.png') %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_url('favicon-32x32.png') %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_url('favicon-96x96.png') %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_url('favicon-16x16.png') %>">
<link rel="manifest" href="<%= image_url('manifest.json') %>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= image_url('ms-icon-144x144.png') %>">
<meta name="theme-color" content="#ffffff">

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success fade in">
      <button data-dismiss="alert" class="close close-sm" type="button">
          <i class="icon-remove"></i>
      </button>
      <strong>Well done!</strong> <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-block alert-danger fade in">
      <button data-dismiss="alert" class="close close-sm" type="button">
          <i class="icon-remove"></i>
      </button>
      <strong>Oh snap!</strong> <%= flash[:error] %>
    </div>               
<% end %>  
<% if flash[:alert] %>
    <div class="alert alert-block alert-danger fade in">
      <button data-dismiss="alert" class="close close-sm" type="button">
          <i class="icon-remove"></i>
      </button>
      <strong>Oh snap!</strong> <%= flash[:alert] %>
    </div>               
<% end %>  
<% if flash[:warning] %>
    <div class="alert alert-warning">
      <strong>Oh snap!</strong> <%= flash[:warning] %>
    </div>               
<% end %>  

app/views/shared/links/_campaigns_links.html.erb
<div class="content">
    <div class="container-fluid">

		<div class="row">
			<div class="col-md-2">
				<%- if controller_name == 'campaigns' && action_name == 'index' %>
				  <%= link_to "New Campaign", new_campaign_path, class: "btn btn-success btn-fill btn-main" %><br />
				<% end -%>
			</div>			
		</div>
    </div>
</div>                    

app/views/shared/links/_companies_links.html.erb
<div class="content">
    <div class="container-fluid">

		<div class="row">
			<%- if controller_name == 'companies' && action_name == 'index' %>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">			
					<%= link_to "New Company", new_company_path, method: :get, class: "btn btn-primary btn-fill btn-main" %><br />
				</div>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
					<% if current_user.companies.present? %>
						<%= link_to "New Campaign", new_campaign_path, class: "btn btn-success btn-fill btn-main" %><br />
					<% end %>						
				</div>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
					<% if current_user.companies.present? && current_user.role == "administrator" %>
						<%= link_to "Flyers", flyers_path, class: "btn btn-success btn-fill btn-main" %><br />
					<% end %>						
				</div>				
			<% end -%>					
			<%- if controller_name == 'companies' && action_name == 'show' && @company.campaigns.size == 0 %>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
					<%= link_to "New Campaign", new_campaign_path(@company), class: "btn btn-primary btn-fill btn-main" %><br />
				</div>
			<% end -%>					
		</div>
    </div>
</div>                    

app/views/shared/links/_flyers_links.html.erb
<div class="content">
    <div class="container-fluid">

		<div class="row">
			<%- if controller_name == 'flyers' && action_name == 'index' %>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">			
					<%= link_to "New Company", new_company_path, method: :get, class: "btn btn-primary btn-fill btn-main" %><br />
				</div>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
					<% if current_user.flyers.present? %>
						<%= link_to "New Campaign", new_campaign_path, class: "btn btn-success btn-fill btn-main" %><br />
					<% end %>						
				</div>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
					<% if current_user.flyers.present? && current_user.role == "administrator" %>
						<%= link_to "Flyers", flyers_path, class: "btn btn-success btn-fill btn-main" %><br />
					<% end %>						
				</div>				
			<% end -%>					
			<%- if controller_name == 'flyers' && action_name == 'show' && @company.campaigns.size == 0 %>
				<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
					<%= link_to "New Campaign", new_campaign_path(@company), class: "btn btn-primary btn-fill btn-main" %><br />
				</div>
			<% end -%>					
		</div>
    </div>
</div>                    

app/views/shared/links/_links_form.html.erb
<%- if controller_name == 'companies' && action_name != 'index' %>
  <%= link_to "Menu", companies_path, class: "btn btn-primary btn-fill" %><br />
<% end -%>

app/views/shared/links/_runs_links.html.erb
<%- if controller_name == 'runs' && action_name == 'index' %>
<div class="content">
    <div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-2 col-md-2">
				<%= link_to "New Print", new_campaign_run_path, class: "btn btn-success btn-fill btn-main" %><br />				
			</div>		
			<div class="col-xs-12 col-sm-2 col-md-2">
				<%= link_to "Back", companies_path, class: "btn btn-warning btn-fill btn-main" %><br />				
			</div>				
		</div>
    </div>
</div>                    
<% end -%>

<%- if controller_name == 'runs' && action_name == 'show' %>
<div class="row">
	<div class="col-xs-12 col-sm-2 col-md-1">
		<%= link_to "Back", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>		
	</div>						
	<div class="col-xs-12 col-sm-2 col-md-1">
		<%= link_to "Print Fliers", campaign_run_path(@campaign, @run, format: "pdf"), class: "btn btn-success btn-fill btn-main" %><br />		
	</div>									
</div>
<% end %>

app/views/shared/partials/_alert.html.erb
<div class="alert alert-warning">
  <button data-dismiss="alert" class="close close-sm btn-fill" type="button">
      <i class="icon-remove"></i>
  </button>
  <strong>Warning!</strong> Are you sure you want to delete the following <%= text %>?
</div> 

app/views/shared/partials/_formfooter.html.erb
                </div>
            </div>
        </div>
    </div>
</div>                    

app/views/shared/partials/_formheader.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
    
    				

app/views/shared/partials/_formparagraph.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title"><%= yield(:paragraph) %></h4>
                    </div>

app/views/shared/partials/_formsubheader.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
          

app/views/shared/partials/_paragraph.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
    				