config/routes.rb
Rails.application.routes.draw do
  	devise_for :users

  	get "ads/:id", to: 'application#show'
	resources :companytypes, :ads

	resources :companies do 
		resources :flyers
	end

	resources :campaigns do 
		resources :runs
	end

	resources :qr_codes, only: [:new, :create]
	
	# companies 
	get "companies/:id/delete", to: 'companies#delete', as: 'delete_company'
	get "campaigns/:id/delete", to: 'campaigns#delete', as: 'delete_campaign'
	#get "runs/:id/download", to: 'companies#download', as: 'download_run'

	# runs
	get "runs/:id/delete", to: 'runs#delete', as: 'delete_run'
	get "runs/:id/newstatus", to: 'runs#newstatus', as: 'newstatus_run'
	post "/runs/:id/newstatus", to: 'runs#changestatus', as: 'changestatus_run'

	# flyers
	get "flyers", to: 'flyers#index', as: "flyers"
	post "flyers/:id/confirm", to: 'flyers#confirm', as: "confirm_flyer"
	delete "flyers/:id", to: 'flyers#destroy', as: "destroy_flyer"

	# landing page
	post "landings", to: 'landings#createSubscription'
	
	root :to => "landings#index"  
end

app/models/run.rb
class Run < ApplicationRecord
	require 'prawn'

	belongs_to :campaign
	belongs_to :language
	has_many :prints, inverse_of: :run, :dependent => :destroy
	has_many :ads, :dependent => :destroy

	accepts_nested_attributes_for :ads, :prints

	validates_presence_of :campaign_id, :city, :location
	#validates :ownads, numericality: { greater_than_or_equal_to: 0, less_than: 75}
	#validates :runprintnumber, numericality: { greater_than: 0, less_than: 80}
	#validates_with RunValidator, fields: [:current_user, :campaign_id, :status]

	def self.nextStatus(run)
		case run.status
		when "to distribute"
			return "completed"
		end
	end

	def self.operator(num, den)
		unless num == 0 || den.size == 0
			ads = (num / den.size).to_i 
			return ads 
		end
	end

  	def self.createAds(run)
	    campaign = run.campaign
	    company = campaign.company  		

	    run.ownads.times do
	      Ad.create(:company_id => company.id, :run_id => run.id, :selfpromotion => true, :visits => 0)
	    end

		if run.ownads < run.runprintnumber
		    otherads = run.runprintnumber - run.ownads
		    firstgroup = (otherads*0.70).ceil
		    secondgroup = otherads - firstgroup 

		    campaigns = Campaign.filtered(run)
		    campaigns = campaigns.joins(:runs).where('runs.status' => "completed").distinct
		    
		    campaigns = campaigns.order(ratio_visits: :desc, created_at: :asc) # ads_received: :asc, 

		    campaigns = Campaign.filtered(run) if campaigns.size == 0 || firstgroup > campaigns.size

		    if firstgroup > campaigns.size
		    	ads = Run.operator(firstgroup, campaigns)
		    else
		    	numberofcompanies = ( firstgroup * 0.5 ).to_i
		    	campaigns = campaigns.limit(numberofcompanies)
		    	ads = 2
		    end

			Ad.postMultiple(campaigns, ads, run)

		    if firstgroup.odd? 
		      Ad.create(:company_id => campaigns[0].company.id, :run_id => run.id, :selfpromotion => false, :visits => 0)
		      campaigns[0].ads_received += 1
		      campaigns[0].save
		    end

			campaigns = Campaign.filtered(run)
			campaigns = campaigns.limit(secondgroup) if campaigns.size > secondgroup 

			ads = Run.operator(secondgroup, campaigns)    
		    Ad.postMultiple(campaigns, ads, run) unless secondgroup == 0
		end
 	end

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy, :delete]
  before_action :set_campaign, only: [:new, :create, :show, :edit, :update]
  before_action :set_companies, only: [:new, :edit, :create]

  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all.where.not(:status => "completed")
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
    @campaign = Campaign.find(params[:campaign_id]) if params[:campaign_id].present?
    @ads = @run.ads
    language = @run.language
    
    respond_to do |format|
      format.html
      format.pdf do
        pdf = RunPdf.new(@run, @ads, confirmed: true )
        send_data pdf.render, filename: "Print Order N.#{@run.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
    @run.update(:status => "to distribute")
    flash[:warning_run] = "Now remember to check the Print Order as completed after giving away all the fliers with the icon"  
  end

  # GET /runs/new
  def new
    @run = Run.new
    3.times do 
      @run.prints.build
    end
  end

  # GET /runs/1/edit
  def edit  
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)  

    printamount = 0
    company_id = nil
    @run.prints.each do |print|
      company_id = print.company_number unless print[:company_number] == nil
      printamount += print.print unless print.print.nil?
    end

    unless company_id == nil # printamount == 0 ||
      if @run.save
        user_companies = Company.joins(:users).where('users.id' => current_user.id)
        @run.prints.each do |print|
          boolean = false
          if print.company_number.present?
            company = Company.find(print.company_number) 
            boolean = true if user_companies.where(:id => print.company_number).present?
            Ad.postSimple(company, @run, boolean)
          end
        end
        flash[:warning_run] = 'The Print Order was successfully created, you can click on the download icon to open the file or download it. REMEMBER: If using MOZILLA open the file with Adobe outside the browser, as Mozilla give some problems when printing. You can open the file and dowload it with the following icon: ' 
        redirect_to companies_path
      else
        flash[:error] = "The run was not saved"
        render "new"
      end
    else
      flash[:error] = "You need to include at least one company and number of copies to print"         
      render "new"
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to companies_path, notice: 'Run was successfully updated.' }
        format.json { render companies_path, status: :ok, location: @run }
      else
        #binding.pry
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end  


  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to companies_path, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def newstatus
    flash[:warning] = "Warning! You should change this status only when you gave away all fliers!"
    @run = Run.find(params[:id])    
  end

  def changestatus
    @run = Run.find(params[:id])
    @run.status = Run.nextStatus(@run)

    respond_to do |format|
      if @run.save
        format.html { redirect_to companies_path, notice: "The status was changed to #{@run.status}." }
        flash[:warning_campaign] = "If you want to give away more fliers you should create a new print order by clicking on the print icon"
      else
        format.html { render :newstatus, error: 'The status was not changed, the application had an error' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    def set_companies
      @companies = Company.all.joins(:flyers).where.not("flyers.image" => nil).where("flyers.confirmed" => true).distinct    
    end

    def set_campaign
      @campaign = Campaign.find(params[:campaign_id]) if params[:campaign_id].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:campaign_id, :runprintnumber, :ownads, :city, :location, :language_id, prints_attributes: [:id, :company_number, :print]) #company_runs_attributes: [:run_id, :company_id, :printnumber]
    end

    def print_number
      params.require("printnumber").permit(:first, :second, :third)
    end

    def ad_params
      params.require(:run).require(:ads_attributes).permit!
    end

    def clean_params
      _params = run_params.delete_if { |k, v| 
        v.empty? if k == "print_attributes" || k == "print"}
    end

end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.erb
<%= simple_form_for(@run) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/runs/delete.html.erb
<% header("runs","Delete Print Order") %>
<%= render "shared/partials/alert", text: @text %>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
               <h2><%= yield(:runs) %></h2>
            </header>
            <div class="panel-body">
            <%= link_to "Delete", campaign_run_path(@run), :method => :delete, :class => "btn btn-warning wideButton btn-fill btn-main" %>
            <%= link_to "Cancel", companies_path, :class => "btn btn-primary wideButton btn-fill btn-main" %>
            </div>
        </section>   
    </div>
</div>

app/views/runs/edit.html.erb
<% header("runs","Edit Print Settings") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:runs) %></h4>
</div>            
<div class="content">
    <%= simple_form_for [@campaign, @run] do |f| %>
      <%# if @run.errors['base'].present? %>
        <!--span class="help-block error"><%#= @run.errors['base'][0] %></span-->
      <%# end %>
      <%= render 'partials/error_messages', object: @run %>
      <div class="form-group select required form-group-fix">
        <%= f.label :campaign_id %>
        <% if @campaign.present? %>
          <%= f.select(:campaign_id, current_user.campaigns.collect {|p| [ p.name, p.id ]}, {:selected => @campaign.id }, {:class => "form-control"}) %> 
        <% else %>
          <%= f.select(:campaign_id, current_user.campaigns.collect {|p| [ p.name, p.id ]}, {:prompt => "select a campaign" }, {:class => "form-control"}) %> 
        <% end %>
      </div>      

      <%= f.fields_for :prints do |print| %>
        <%= print.label :company_number, "Select a company for the fliers" %>
        <%= print.select(:company_number, @companies.collect {|p| [ p.name, p.id ]}, {:prompt => "Please Select a company or leave blank" }, {:class => "form-control"}) %>
        <%#= print.input :print, label: "Number of Fliers" %>
      <% end %>
      <div class="form-group form-group-fix">
        <%= f.label :city, "* City", class: "col-sm-12 control-label labels" %>  
        <%= f.text_field :city, {class: "form-control", value: current_user.city} %>  
      </div>
      <%#= f.input :city, input_html: {:value => current_user.city} %>
      <%= f.input :location, label: "Description of the locations" %>
      <%= f.association :language, label: "Language for the Fliers", selected: @run.language.id, default: "EN"  %>
      <% if controller_name == "companies" %>
      <%= link_to "Hide", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>      
      <% else %>
      <%= link_to "Back", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>
      <% end %>
      <%= f.button :submit, "Print Fliers", class: "btn btn-info btn-fill pull-right btn-main" %>
      <div class="clearfix"></div>
    <% end %>
</div>
<%= render partial: "shared/partials/formfooter" %>

app/views/runs/index.html.erb
<% run_last = Run.last %>
<% if @runs.present? %>
<%# if flash[:warning_run] %>
    <!--div class="alert alert-warning">
      <strong>Oh snap!</strong> <%#= flash[:warning_run] %>
    </div-->               
<%# end %>  

<% if flash[:warning_run] %>
    <div class="alert alert-warning">
      <strong>Great!</strong> <%= flash[:warning_run] %>  
      <% if run_last.status == "to print" %>
        <i class="fa fa-download fa-2x messageIcon" aria-hidden="true"></i>
      <% elsif run_last.status == "to distribute" %>
        <i class="fa fa-check fa-2x messageIcon" aria-hidden="true"></i>
      <% end %>
    </div>               
<% end %>  

<% if flash[:error_run] %>
    <div class="alert alert-block alert-danger fade in">
      <button data-dismiss="alert" class="close close-sm" type="button">
          <i class="icon-remove"></i>
      </button>
      <strong>Oh snap!</strong> <%= flash[:error_run] %>
    </div>               
<% end %>  

<% if @runs.length > 0 %>
<% header("runs#index","Print List") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:runs_index) %></h4>
</div>            
<div class="content table-responsive table-full-width">
    <table class="table table-hover table-striped">
        <thead class="row">
          <th class="halfwidth col-xs-7 col-sm-4 col-md-1">Status</th>
          <th class="hidden-xs hidden-sm">Company</th>
          <th class="hidden-xs col-sm-4">Campaign</th>
          <th class="hidden-xs col-sm-1 numeric">Number of Ads</th>
          <th class="halfwidth options col-xs-5 col-sm-3 col-md-2">Options</th>
        </thead>
        <tbody class="row">
            <% @runs.each do |run| %>
            <% if run.status != "completed" %>
              <tr>
                <td class="halfwidth col-xs-7 col-sm-4 col-md-1"><%= run.status %></td>
                <td class="hidden-xs hidden-sm"><%= run.campaign.company.name %></td>
                <td class="hidden-xs col-sm-4"><%= run.campaign.name %></td>
                <td class="hidden-xs col-sm-1 numeric"><%= run.runprintnumber %></td>  
                <td class="halfwidth options col-xs-5 col-sm-3 col-md-2">
                    <div class="btn-group" id="btn-group">
                    <% if run.status != "to print" && run.status != "completed" %>
                      <%= link_to newstatus_run_path(run), {class: "btn btn-primary", 'rel' => 'tooltip', 'data-placement' => 'top', 'title'=>"Confirm Print as distributed or completed"} do %><i class="fa fa-check-circle-o" aria-hidden="true"></i><% end %>
                     <% end %>
                     <% if run.status != "completed" %>
                     <%= link_to edit_campaign_run_path(run.campaign, run), {class: "btn btn-success", id: "", 'rel' => 'tooltip', 'data-placement' => 'top', 'title'=>"Edit Print"} do %><i class="fa fa-pencil" aria-hidden="true"></i><% end %>

                     <%= link_to delete_run_path(run.id), {class: "btn btn-danger", 'rel' => 'tooltip', 'data-placement' => 'top', 'title'=>"Delete Print Settings"} do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %>
                     
                     <%= link_to campaign_run_path(run.campaign, run, format: "pdf"), {class: "btn btn-primary", 'rel' => 'tooltip', 'data-placement' => 'top', 'title'=>"Open Pdf File"} do %><i class="fa fa-cloud-download" aria-hidden="true"></i><% end %>                   
                    <% end %>
                    </div>
                </td>
              </tr>
            <% end %>
            <% end %>
        </tbody>
    </table>

</div>
<%= render partial: "shared/partials/formfooter" %>
<%= render partial: "shared/links/runs_links" %>
<% end %> <!-- if @runs.present? -->
<% else %>
<%= render partial: "shared/links/runs_links" %>
<% end %>

<!--a href="http://localhost:3000/campaigns/8/runs/33.pdf" download>Export</a-->

app/views/runs/new.html.erb
<% header("runs#new","Print Settings") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:runs_new) %></h4>
</div>            

<div class="content">
    <%= simple_form_for [@campaign, @run] do |f| %>
      <%# if @run.errors['base'].present? %>
        <!--span class="help-block error"><%#= @run.errors['base'][0] %></span-->
      <%# end %>
      <%= render 'partials/error_messages', object: @run %>
      <div class="form-group select required form-group-fix">
        <%= f.label :campaign_id %>
        <% if @campaign.present? %>
          <%= f.select(:campaign_id, current_user.campaigns.collect {|p| [ p.name, p.id ]}, {:selected => @campaign.id }, {:class => "form-control"}) %> 
        <% else %>
          <%= f.select(:campaign_id, current_user.campaigns.collect {|p| [ p.name, p.id ]}, {:prompt => "select a campaign" }, {:class => "form-control"}) %> 
        <% end %>
      </div>      

      <%= f.fields_for :prints do |print| %>
        <%= print.label :company_number, "Select a company for the fliers" %>
        <%= print.select(:company_number, @companies.collect {|p| [ p.name, p.id ]}, {:prompt => "Please Select a company or leave blank" }, {:class => "form-control"}) %>
        <%#= print.input :print, label: "Number of Fliers" %>
      <% end %>
      <div class="form-group form-group-fix">
        <%= f.label :city, "* City", class: "col-sm-12 control-label labels" %>  
        <%= f.text_field :city, {class: "form-control", value: current_user.city} %>  
      </div>
      <%#= f.input :city, input_html: {:value => current_user.city} %>
      <%= f.input :location, label: "Description of the locations" %>
      <%= f.association :language, label: "Language for the Fliers", default:"EN"  %>
      <% if controller_name == "companies" %>
      <%= link_to "Hide", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>      
      <% else %>
      <%= link_to "Back", companies_path, class: "btn btn-primary btn-fill pull-left btn-main" %>
      <% end %>
      <%= f.button :submit, "Print Fliers", class: "btn btn-info btn-fill pull-right btn-main" %>
      <div class="clearfix"></div>
    <% end %>
</div>
<%= render partial: "shared/partials/formfooter" %>

app/views/runs/newstatus.html.erb
<% header("runs#status","Change Status") %>
<%#= render "shared/partials/alert", text: @text %>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
               <h2><%= yield(:run_status) %></h2>
               <p>You should change this status, when you gave away all the fliers</p>
            </header>
            <div class="panel-body">
            <%= link_to "Change Status", changestatus_run_path, :method => :post, :class => "btn btn-warning wideButton btn-fill btn-main" %>
            <%= link_to "Cancel", companies_path, :class => "btn btn-primary wideButton btn-fill btn-main" %>
            </div>
        </section>   
    </div>
</div>

app/views/runs/show.html.erb
<% title "Display Print Order" %>
<%= render "shared/partials/formheader" %>
        <div class="content">
            <%= simple_form_for [@campaign, @run] do |f| %>
              <%= f.association :campaign, disabled: true %>
              <%= f.input :runprintnumber, disabled: true %>
              <%= f.input :ownads, disabled: true %>
              <%= render partial: "shared/links/runs_links" %>
              <div class="clearfix"></div>
            <% end %>
        </div>
<%= render partial: "shared/partials/formfooter" %>

<% if @ads.length > 0 %>
<% header("ads","Ads Printed") %>
<%= render "shared/partials/formheader" %>
<div class="header">
    <h4 class="title"><%= yield(:ads) %></h4>
</div>            
<div class="content table-responsive table-full-width">
    <table class="table table-hover table-striped">
        <thead class="row">
          <th class="">Company Name</th>
          <th class="numeric">N.Visits</th>
          <th class="hidden-xs options">SelfPromotion</th>
          <th class="options col-xs-8 col-sm-3 col-md-2">Options</th>
        </thead>
        <tbody class="row">
            <% @ads.each do |ad| %>
            <tr>
              <td class=""><%= ad.company.name %></td>
              <td class="numeric"><%= ad.visits %></td>
              <td class="hidden-xs options">
              <% if ad.selfpromotion %>
              <i class="fa fa-check" aria-hidden="true"></i>
              <% else %>
              <i class="fa fa-times" aria-hidden="true"></i>
              <% end %> 
              </td>
              <td class="options col-xs-8 col-sm-3 col-md-2">
                  <div class="btn-group" id="btn-group">
                   <%= link_to ad_path(ad.id), class: "btn btn-primary" do %><i class="fa fa-arrow-right" aria-hidden="true"></i><% end %>
                  </div>
              </td>
            </tr>
            <% end %>
        </tbody>
    </table>

</div>
<%= render partial: "shared/partials/formfooter" %>
<% else %>
<%= render partial: "shared/links/runs_links" %>
<% end %>